#!/bin/bash 

# Usage information
while [ $1 ]; do 
    case $1 in 
        -h | --help)
        echo "Usage: $(basename $0) [--help] [--outdir example] [--pdf] [--file TeXfile]"
        echo
        echo "If a LaTeX file is not provided, current directory is searched for one."
        echo "Default output directory is 'build'."
        echo "All other arguments are passed directly to pdfpc command line."
        exit 0
        ;;
        -o | --outdir)
        OUTDIR=$2
        shift 2
        ;;
        -p | --pdf)
        PDFFLAG=1
        shift 1
        ;;
        -f | --file)
        TEXFILE=$2
        shift 2
        ;;
        *)
        PCOPTS+="$PCOPTS $1"
        shift 1
        ;;
    esac
done

# Validate TeX file
if [[ -z $TEXFILE ]]; then
    TEXFILE=`ls | grep ".*\.tex$"`
    NUMFILES=`ls | grep ".*\.tex$" | wc -l`
    if [[ $NUMFILES -eq 0 ]]; then
        echo "Warning: no automatic TeX file found, '$TEXFILE'."
        exit 1
    elif [[ $NUMFILES -gt 1 ]]; then
        echo "Error: too many TeX files found, '$TEXFILE'."
        exit 1
    else
        echo "Automatic TeX file found, '$TEXFILE'."
    fi
fi
if [[ ! -e $TEXFILE ]]; then
    echo "Error: TeX file does not exists, '$TEXFILE'."
    exit 1
fi

# Validate output directory
[[ -z $OUTDIR ]] && OUTDIR="build"
[[ ! -d $OUTDIR ]] && mkdir $OUTDIR

# Internal stuff
BASEFILE=${TEXFILE%.*}

# Define commands
PDFLATEX_CMD="pdflatex -synctex=1 -interaction=nonstopmode -output-dir=$OUTDIR $TEXFILE"
BIBTEX_CMD="bibtex $OUTDIR/$BASEFILE"
PDFVIEW_CMD="evince $OUTDIR/$BASEFILE.pdf"
PCVIEW_CMD="pdfpc $PCOPTS $OUTDIR/$BASEFILE.pdf"

# Run commands
$PDFLATEX_CMD
$BIBTEX_CMD
$PDFLATEX_CMD
$PDFLATEX_CMD
if [ $PDFFLAG ]; then 
    $PDFVIEW_CMD & disown
else
    $PCVIEW_CMD & disown
fi

unset TEXFILE NUMFILES OUTDIR BASEFILE PDFLATEX_CMD BIBTEX_CMD PDFVIEW_CMD PCOPTS PCVIEW_CMD

