#!/bin/bash

usage()
{
    echo
    echo "Usage: $(basename $0) [--file file.rpm]"
    echo
    echo "Extract contents from a RPM file."
    echo
}

# Default options
file=

# Get command line options 
while [ "$1" ]; do 
    case "$1" in 
        -h | --help)
        usage
        exit 0
        ;;
        -f | --file)
        file="$2"
        shift 2 
        ;;
        *)
        echo "Error: invalid command line option, $1"
        usage
        exit 1
        ;;
    esac
done

# Validate
if [ -z "$file" ]; then
    echo "Error: no RPM file was provided."
    exit 1
fi
 
if [ "${file##*.}" != "rpm" ]; then
    echo "Error: not a RPM file, \"$file\""
    exit 1
fi

if [ ! -e "$file" ]; then
    echo "Error: RPM file does not exists, \"$file\""
    exit 1
fi

# Run
cmd="rpm2cpio \"$file\" | cpio -i --make-directories"
eval $cmd

unset file cmd

