#!/bin/bash 

usage()
{
    echo
    echo "Usage: $(basename $0) [--help] [--jvm] [--run \"COMMAND\"|SCRIPT.m]"
    echo
    echo "Starts MATLAB interpreter without GUI."
    echo "Command or script can be executed during startup."
    echo "Default is disabled Java Virtual Machine."
    echo
}

# Default options
deskcmd="-nodesktop -nosplash"
jvmcmd="-nodisplay -nojvm"
runcmd=

# Get command line options 
while [ "$1" ]; do 
    case "$1" in 
        -h | --help)
        usage
        exit 0
        ;;
        -j | --jvm)
        jvmcmd=
        shift 1
        ;;
        -r | --run)
        # Check if a script or a command
        if [ "${2##*.}" = "m" ]; then
            runcmd="-r \"try, run('$2'); catch me, fprintf(2, '%s / %s\\n', me.identifier, me.message); exit(1); end\""
        else
            runcmd="-r \"try, $2, catch me, fprintf(2, '%s / %s\\n', me.identifier, me.message); exit(1); end\""
        fi
        shift 2
        ;;
        *)
        echo "Error: invalid command line option, $1"
        usage
        exit 0
        ;;
    esac
done

# Run 
cmd="matlab $deskcmd $jvmcmd $runcmd"
eval $cmd

unset deskcmd jvmcmd runcmd cmd

