#!/bin/bash 

usage()
{
    echo
    echo "Usage: $(basename $0) [--help] [--jvm] [--run COMMAND|SCRIPT]"
    echo
    echo "Default is disabled Java Virtual Machine."
    echo "If a command or script is not provided, MATLAB interpreter is started."
    echo
}

# Default options
jvmcmd="-nodisplay -nojvm"
runcmd=

# Get command line options 
while [ "$1" ]; do 
    case "$1" in 
        -h | --help)
        usage
        exit 0
        ;;
        -j | --jvm)
        jvmcmd=
        shift 1
        ;;
        -r | --run)
        runcmd="-r \"try, run('$2'); catch me, fprintf(2, '%s / %s\\n', me.identifier, me.message); exit(1); end, exit(0)\""
        shift 2
        ;;
        *)
        echo "Error: invalid command line option, $1"
        usage
        exit 0
        ;;
    esac
done

# Run 
cmd="matlab -nodesktop -nosplash $jvmcmd $runcmd"
eval $cmd

unset jvmcmd runcmd cmd

