#!/bin/bash

usage()
{
    echo
    echo "Usage: $(basename $0) [--help] [--protocol PROTOCOL] [--mirror] [--direction DIRECTION_ID]"
    echo
    echo "Change monitor configuration."
    echo "Default is extended screen."
    echo "Direction ID is ignored if mirror option is set."
    echo
    echo "Protocols:"
    echo " 0 -> LVDS1 (default)"
    echo " 1 -> VGA"
    echo " 2 -> HDMI"
    echo
    echo "Direction IDs for extended mode:"
    echo " 0 -> left (default)"
    echo " 1 -> above"
    echo " 2 -> right"
    echo " 3 -> below"
    echo
}

# Default options
mon_proto=0
mirror=0
direction_id=0

# Get command line options 
while [ "$1" ]; do 
    case "$1" in 
        -h | --help)
        usage
        exit 0
        ;;
        -p | --protocol)
        mon_proto=$2
        shift 2
        ;;
        -m | --mirror)
        mirror=1
        shift 1
        ;;
        -d | --direction)
        direction_id=$2
        shift 2
        ;;
        *)
        echo "Error: invalid command line option, $1"
        usage
        exit 1
        ;;
    esac
done

# Validate        
if [ $mon_proto -lt 0 ] && [ $mon_proto -gt 2 ]; then
    echo "Error: invalid protocol value."
    exit 1 
fi

if [ $direction_id -lt 0 ] || [ $direction_id -gt 3 ]; then
    echo "Error: invalid direction value."
    exit 1 
fi

# NOTE: need to check if VGA and/or HDMI are available options.

# Select monitor protocol and position
if [ $mirror -eq 0 ]; then
    # Extended mode
    if [ $direction_id -eq 0 ]; then
        rel_pos="--left-of LVDS1"  
    elif [ $direction_id -eq 1 ]; then
        rel_pos="--above LVDS1"  
    elif [ $direction_id -eq 2 ]; then
        rel_pos="--right-of LVDS1"  
    elif [ $direction_id -eq 3 ]; then
        rel_pos="--below LVDS1"  
    fi
elif [ $mirror -eq 1 ]; then
    # Mirror mode
    rel_pos="--pos 0x0"
fi

# Protocol
lvds="--primary --auto --pos 0x0 --rotate normal"
vga="--off"
hdmi="--off" 
if [ $mon_proto -eq 0 ]; then
    if [ $(xrandr --listactivemonitors | grep 'Monitors' | awk '{ print $NF }') -eq 1 ]; then
        exit 0 
    fi
elif [ $mon_proto -eq 1 ]; then
    vga="--auto $rel_pos --rotate normal"
elif [ $mon_proto -eq 2 ]; then
    hdmi="--auto $rel_pos --rotate normal"
fi

# Run
cmd="xrandr --output VIRTUAL1 --off --output DP1 --off --output HDMI1 $hdmi --output VGA-1-2 --off --output LVDS1 $lvds --output VGA1 $vga"
eval $cmd

unset mon_proto mirror direction_id rel_pos lvds vga hdmi cmd

