#!/bin/bash

# Adds an array of paths to a given environment variable.
# The variable does not have to exist and duplicate paths are prevented.

# ### IMPORTANT NOTE ###
# This program is not to be used interactively.
# The 'exit' statement should never appear on this code as it is sourced
# by .bashrc during login, thus exiting the login shell right after user
# logs in. If this happens, the brute force solution is to press Ctrl+C
# immediately after user logs in (it may take several tries).

# Validate arguments
if [[ $# -ne 2 ]]; then
    return 0
fi

# Parse argument strings into variables (variable indirection)
ENVVAR=${!1}
declare -a PATHARR=(${!2})

# Extract new paths not found in env var
IDX=0
declare -a NEWPATHS
for path in ${PATHARR[@]}; do
    if [[ ! $ENVVAR =~ ${path}(:.*)?$ ]]; then
        NEWPATHS[$IDX]=$path
        IDX=$(( IDX + 1 ))
    fi
done

# Join new paths as a string
[[ -z ${NEWPATHS} ]] && return 0

if [[ ${#NEWPATHS[@]} -eq  1 ]]; then
    STRPATHS=$NEWPATHS
else
    STRPATHS=$(IFS=":"; echo "${NEWPATHS[*]}")
fi

# Add new paths to env var 
if [[ -z $ENVVAR ]]; then
    export "${1}=${STRPATHS}"
else
    export "${1}=${STRPATHS}:${ENVVAR}"
fi

unset ENVVAR PATHARR IDX NEWPATHS STRPATHS

