#!/bin/bash 

usage()
{
    echo
    echo "Usage: $(basename $0) [--help] [--wallpaper WALLPAPER_ID]"
    echo
    echo "Change wallpaper image."
    echo
    echo "Wallpaper IDs:"
    local wid=0
    for wfile in "$@"; do 
        if [ $wid -eq 0 ]; then
            echo " $wid -> $wfile (default)"
        else
            echo " $wid -> $wfile"
        fi
        wid=$(( wid + 1 ))
    done
    echo
}

# Default options 
wall_id=0
wall_files=(
"$HOME/Documents/wallpapers/lubuntu-eduardo-wallpaper-1920x1080.png"
"$HOME/Documents/wallpapers/black_1920x1080.png"
"$HOME/Documents/wallpapers/purple_1920x1080.png"
"$HOME/Documents/wallpapers/gray_1920x1080.png"
)

# Get command line options 
while [ "$1" ]; do 
    case "$1" in 
        -h | --help)
        usage ${wall_files[@]}
        exit 0
        ;;
        -w | --wallpaper)
        wall_id=$2
        shift 2
        ;;
        *)
        echo "Error: invalid command line option, $1"
        usage ${wall_files[@]}
        exit 1
        ;;
    esac
done

# Validate
if [ $wall_id -lt 0 ] || [ $wall_id -ge ${#wall_files[@]} ]; then
    echo "Error: invalid wallpaper ID value."
    exit 1
fi

wall_file="${wall_files[$wall_id]}"
if [ ! -e "$wall_file" ]; then
    echo "Error: wallpaper file does not exists, \"$wall_file\""
    exit 1
fi

# Run
cmd="pcmanfm --set-wallpaper=\"$wall_file\" --wallpaper-mode=stretch"
eval $cmd

unset wall_id wall_file wall_files cmd 

