#!/bin/bash

# This script is executed during LightDM X11 display at startup.
# Used in: /usr/share/lightdm/lightdm.conf.d/20-lubuntu.conf

# Set display to main monitor only
if [ $(xrandr --listactivemonitors | grep 'Monitors' | awk '{ print $NF }') -gt 1 ]; then
    /home/edponce/monitor_change
fi

# Enable horizontal two finger scroll for Synaptic touchpad
if [ $(synclient -l | grep 'HorizTwoFingerScroll' | awk '{ print $NF }') -eq 0 ]; then
    synclient HorizTwoFingerScroll=1
fi

# Enable numlock
if [ "$(numlockx status | awk '{ print $NF }')" = "off" ]; then
    numlockx on
fi

